### ISSUE TITLE
Evaluate using a logger interface instead of golang stdlib log package

### ISSUE THREAD

**Issue by wneessen** [wneessen/go-mail#112]
### Is your feature request related to a problem? Please describe.

As stated in https://github.com/wneessen/go-mail/pull/102#issuecomment-1411956040, we should rather use a logger intreface, so the user can decide which kind of logger they want to use.

### Describe the solution you'd like

We provide a simple `Logger` interface that can be implemented easily:

```go
type Logger interface {
	Errorf(format string, v ...interface{})
	Warnf(format string, v ...interface{})
	Infof(format string, v ...interface{})
	Debugf(format string, v ...interface{})
}
```

**Comment by james-d-elliott** [comment]
Theoretically multiple can be supported relatively easily using the method described in the comment. As users can just provide a decorator that implements the `Logger` for their particular logging provider. So overall this is a really nice idea.
