### ISSUE TITLE
allow creating html mail with plain text part

### ISSUE THREAD

**Issue by lublak** [wneessen/go-mail#125]
### Is your feature request related to a problem? Please describe.

Currently you can create a html mail or a plain text mail.
Without fallback solution.

### Describe the solution you'd like

It would be nice to have an option to create a html body with a fallback plain text (for email programs that are not supporting html)

https://gist.github.com/tylermakin/d820f65eb3c9dd98d58721c7fb1939a8

**Comment by james-d-elliott** [comment]
Pretty sure this is already possible I'm out at the moment but will show code in about 40 mins if someone else doesn't

**Comment by wneessen** [comment]
@james-d-elliott is right. You can accomplish that with the [AddAlternative*](https://pkg.go.dev/github.com/wneessen/go-mail#Msg.AddAlternativeString) methods. You assign a main body part and an alternative body part. 

A full example, using the Template methods can be found in the bulk mailer example on the go-mail website:
https://go-mail.dev/examples/bulk-mailer/#hl-0-86

**Comment by james-d-elliott** [comment]
Damn, I forgot about this, thanks Winni.

**Comment by lublak** [comment]
@wneessen thanks :) i will try it out!
