### ISSUE TITLE
Sync upstream changes to net/smtp

### ISSUE THREAD

**Issue by wneessen** [wneessen/go-mail#126]
### Is your feature request related to a problem? Please describe.

Upstream `net/smtp` has received a very minior change:
https://github.com/golang/go/commit/eb2bc919760d7a3e5ffd6022756cd7bda2f2dc63#diff-2306577ab99a109f7df7c52a6ba6d4c22bfe20168bb22692920fc95c77bb4aed

This should be synced to our port as well.

### Describe the solution you'd like

N/A

**Comment by james-d-elliott** [comment]
Related; https://github.com/golang/go/issues/58141
