### ISSUE TITLE
Add method to remove any attachment/embed

### ISSUE THREAD

**Issue by wneessen** [wneessen/go-mail#147]
### Is your feature request related to a problem? Please describe.

Based on [this issue](https://github.com/go-gomail/gomail/issues/187) it would be nice to have a method that removes all attachments/embeds that are currently attached to a `Msg`. This should be a simple change.

### Describe the solution you'd like

I am thinking about three seperate methods:

- `Msg.UnsetAllAttachments()`: That removes all currently assigned attachments
- `Msg.UnsetAllEmbeds()`: That removes all currently assigned embeds
- `Msg.UnsetAllParts()`: That removes all currently assigned attachments and embeds

**Comment by leahoop** [comment]
Have these methods been assigned yet? If not maybe I can a try

**Comment by wneessen** [comment]
@leahoop Feel free to give it a try! Appreciate the initiative!

**Comment by leahoop** [comment]
thanks, it's my pleasure

**Comment by wneessen** [comment]
Merged to main.
