### ISSUE TITLE
[Feature Req] Interface that accept To/CC with a single string

### ISSUE THREAD

**Issue by suntong** [wneessen/go-mail#152]
### Is your feature request related to a problem? Please describe.

Please consider adding/allowing passing a single string to To/CC. Currently there is an extra check preventing it:

`failed to set To address: failed to parse mail address "a1@gmail.com,a2@gmail.com", mail: expected single address, got ",a2@gmail.com"`

When using

`if err := m.To("a1@gmail.com,a2@gmail.com"); err != nil {`

in https://go-mail.dev/getting-started/introduction/#hl-5-13

Reason being:

- It is perfectly fine to set the "`To:`" header to something like `"Alice <alice@example.com>, Bob <bob@example.com>, Eve <eve@example.com>"` _in plain email_, so such extra checking is too restrictive.
- I understand that there might be extra checking on the email address format checking, but since the basic text based unix email doesn't check it, such extra checking can be optional, IMHO. After all, if the user made mistakes in their to/cc email address, they will know eventually.
- And the most important thing is, to add more recipients, I have to _**change my Go code**_ to do that, whereas the common sense/practice is to change data, not to change code, when covering different cases.

### Describe the solution you'd like

Adding/allowing passing a single string to To/CC.

I can work on PR for that.

**Comment by wneessen** [comment]
Hi @suntong,

thanks for the feature request. I see you need here and I think it might be a good addition to go-mail. To not break any current code, I suggest something like `m.ToFromString()` and `m.CcFromString()`. If you'd like a provide a PR, that'll be appreciated. Otherwise I'll put this request on the todo list for the next release.

**Comment by suntong** [comment]
Thanks for the confirmation. I'll make a try...

**Comment by james-d-elliott** [comment]
This could be handled locally fairly easily too:

```go
if err := m.To(strings.Split("a1@gmail.com,a2@gmail.com", ",")...); err != nil {
```

**Comment by suntong** [comment]
indeed!

**Comment by wneessen** [comment]
Thanks for the PR @suntong, but I feel that adding complexity `SetAddrHeader` should not be the desired solution. As either `To()`, `Cc()` and `Bcc()` already accept slices of strings, @james-d-elliott's solution should probably preferred by just adding helper methods like:

```go
func (m *Msg) ToFromSimpleString(v string) error {
    return m.To(strings.Split(v)...);
}
```

or something similar. This let's us stay true with the KISS principle.

**Comment by suntong** [comment]
Yeah, agree.

**Comment by suntong** [comment]
> should probably be preferred by just adding helper methods like ...
> Otherwise I'll put this request on the todo list for the next release.

That'd be great, if possible. 

Reopen it again, and feel free to close it anytime.
