### ISSUE TITLE
Method SetBodyHTML, without Template

### ISSUE THREAD

**Issue by suntong** [wneessen/go-mail#154]
### Is your feature request related to a problem? Please describe.

The `m.SetBodyHTMLTemplate` would make it very difficult to programmatically switching between sending plain text or html email, while having a `m.SetBodyHTML` would make the task trivial. 

### Describe the solution you'd like

Can we have `m.SetBodyHTML` that accept a html body string, instead of a template _and_ a `d interface{}` please? 

Please consider. thx.
I can work on the PR.

**Comment by wneessen** [comment]
Hi @suntong,

you can already send simple HTML mails by just using `SetBodyString()` with `TypeTextHTML` as your content type. Example: `m.SetBodyString(TypeTextHTML, "<p>This is HTML</p>"`. If you wanna combine HTML and Text parts, you can make use of `m.AddAlternativeString()` with the alternative content type.

References: 
- [SetBodyString](https://pkg.go.dev/github.com/wneessen/go-mail#Msg.SetBodyString)
- [AddAlternativeString](https://pkg.go.dev/github.com/wneessen/go-mail#Msg.AddAlternativeString)

The reason we have HTML and Text of the functions that accept templates is, that they make use of the two different template packages from the standard library and therefore need to be distinguished by name.

**Comment by suntong** [comment]
Oh, thanks!
