### ISSUE TITLE
No easy way to determine if e-mail was send

### ISSUE THREAD

**Issue by mitar** [wneessen/go-mail#166]
### Is your feature request related to a problem? Please describe.

I am sending [multiple e-mails in bulk](https://go-mail.dev/examples/bulk-mailer/). The issue is that if there is an error on `Client.Send` (and thus also `Client.DialAndSend`) there is no easy way to determine which e-mails were send (only which e-mails were not). I can inspect `m.HasSendError()` to know that the e-mail was not send. But I do not know if it is send. For example, `Client.Send` could fail on `c.checkConn` and never even attempt to send any e-mail.

### Describe the solution you'd like

I suggest that at the beginning of `Client.Send`, for all messages `Msg.sendError` should be set to a non-nil value, something like `SendError{Reason: ErrNotAttempted}`. Then it would be clear if `Msg.sendError` is `nil` that e-mail was send.

### Describe alternatives you've considered

I could be calling `Client.Send` on each message individually myself. But that then calls `checkConn` again and again.

**Comment by wneessen** [comment]
Thanks for the suggestion @mitar. I agree that this would be a good improvement. I'll do some testing and will come up with something accordingly.

**Comment by mitar** [comment]
Perfect as well! Thanks!

**Comment by mitar** [comment]
> Since errors are appendable

BTW, the way how code currently does "appending" is really ... bad. I think. As an [author of one of (I believe) good errors packages for Go](https://gitlab.com/tozd/go/errors) the issue with current approach is that you create a tree of joined errors. Every time you call `errors.Join` it creates a new error with two child errors.

A better way I think would be to have a slice of errors you append to and join just once at the end (you could even join in `defer` and set a named return value. `errors.Join` also discards all nil errors, so you could just be collecting all errors without checking (unless it influences the code flow). I did something similar [here](https://gitlab.com/charon/charon/-/blob/main/mail.go?ref_type=heads#L62-74).

**Comment by wneessen** [comment]
Thanks for the feedback. I agree it's not the most efficient way we're doing it right now. Definetely something that can and should be improved in the future.
