### ISSUE TITLE
Remove default headers

### ISSUE THREAD

**Issue by jimtsao** [wneessen/go-mail#212]
### Is your feature request related to a problem? Please describe.

Consider removing default headers that are not required as part of any RFCs

- User-Agent
- X-Mailer
- Message-ID

### Describe the solution you'd like

Change behavior to opt-in, eg

1. `SetUserAgent()` or `SetDefaultUserAgent()`
2. Remove `noDefaultUserAgent` on Message struct and `WithNoDefaultUserAgent` msgOption

### Describe alternatives you've considered

Expose a method on Message struct to allow unsetting message headers. So at least middleware is able to modify headers.

### Additional context

Consider also security implications of default message id that may expose information about host machine

**Comment by jimtsao** [comment]
Consider also security implications of default message id that may expose information about host machine

**Comment by wneessen** [comment]
Hi @jimtsao,

thanks for opening this issue. 

Regarding the Message-ID: Even though the RFC describes it as "optional", it also states that it SHOULD be set. See: [https://www.rfc-editor.org/rfc/rfc2822#section-3.6.4}(RFC 2822 Section 3.6.4). For that reason I don't think it would be a good decision to remove the default. 

For the User-Agent: We already offer the option to not set it via the (as you mentioned) `WithNoDefaultUserAgent` option. I see no reason to change the default behaviour.

**Comment by jimtsao** [comment]
No worries, will close for now.
