### ISSUE TITLE
Enhanced SCRAM-SHA support

### ISSUE THREAD

**Issue by wneessen** [wneessen/go-mail#242]
### Is your feature request related to a problem? Please describe.

Based on this issue: https://github.com/go-gomail/gomail/issues/198 we might want to evaluate if this is something that would benefit go-mail.

### Describe the solution you'd like

TBD

**Comment by drakkan** [comment]
Hi,

I started working on this feature a while ago. Attached is my WIP. I remember testing it with Dovecot and it worked. I don't have time/motivation to finish this work in the near future, sorry. If I remember correctly channel bindings could be problematic.

I hope it's useful as a starting point for people who are interested.

[auth_scram.zip](https://github.com/user-attachments/files/15766174/auth_scram.zip)

**Comment by wneessen** [comment]
Thanks a lot @drakkan. Having some ground work at hand will certainly help. Much appreciated.

**Comment by Neustradamus** [comment]
@wneessen: Good job, thanks a lot!

**Comment by Neustradamus** [comment]
@wneessen: Good job, thanks a lot!

Linked to:
- https://github.com/scram-sasl/info/issues/1

**Comment by Neustradamus** [comment]
@wneessen, @drakkan: Good job, thanks a lot!

Linked to:
- https://github.com/scram-sasl/info/issues/1
