### ISSUE TITLE
Parsing rfc5322 example A11 fails

### ISSUE THREAD

**Issue by Henning1** [wneessen/go-mail#271]
### Description

Hi,
 
I tried to parse rfc5322 example A11 with `gomail.EMLToMsgFromString(..)` and the method returned the errror `failed to parse EML contents: failed to parse EML body parts: failed to extract content type: mime: no media typ`.

Are there known limitations to the parser I am not aware of or is this a bug?

Best,
Henning

### To Reproduce

1. Get example message A1.1 from [rfc](https://datatracker.ietf.org/doc/html/rfc5322#appendix-A)
2. Parse it with `gomail.EMLToMsgFromString(..)`
3. Inspect error message

### Expected behaviour

Should parse successfully

**Comment by wneessen** [comment]
Thanks for the report @Henning1. The EML parser is fairly new and probably has some cases I didn't consider. This is likely an oversight. I'll have a look at the example and provide a fix soon.
