### ISSUE TITLE
Allow bypass plain auth tls check

### ISSUE THREAD

**Issue by lublak** [wneessen/go-mail#342]
### Is your feature request related to a problem? Please describe.

Currently with use a special smtp tunnel without encryption and plain text (we have old hardware).
With the tunnel we secure the connection.
Currently there is not option to bypass it in your library:

https://github.com/wneessen/go-mail/blob/main/smtp/auth_plain.go#L41

### Describe the solution you'd like

An option to set plain text without require tls and localhost.

### Describe alternatives you've considered

Currenlty i copied the code and use `SetSMTPAuthCustom`

**Comment by wneessen** [comment]
PR #344 implements two new `SMTPAuthType` types: `SMTPAuthPlainNoEnc` and `SMTPAuthLoginNoEnc`. These allow for PLAIN and LOGIN auth via unencrypted channels.

**Comment by lublak** [comment]
@wneessen awesome :) thank you!
