### ISSUE TITLE
Allow sending mails without authentication

### ISSUE THREAD

**Issue by kolaente** [wneessen/go-mail#36]
### Is your feature request related to a problem? Please describe.

There are users who run their smtp servers without authentication (for example in a private network). Currently, this package is unable to connect to such mail servers.

I've tried a few things and got different error messages as a result:

1. With auth type plain and no username/password:

```
dial failed: SMTP AUTH failed: 535 Incorrect authentication data
```

2. Without the `mail.WithSMTPAuth` option or uncommenting https://github.com/wneessen/go-mail/blob/main/client.go#L327-L329:

```
send failed: sending RCPT TO command failed: 550 relay not permitted
```

3. With an empty password and username.

None of these three things seem to work.

Related https://github.com/go-vikunja/api/issues/34#issuecomment-1181627930

### Describe the solution you'd like

Ideally, there would be an option like `mail.WithoutAuthentication` which does not even try to authenticate and instead just sends the mail straight away. I thought this would work when removing lines https://github.com/wneessen/go-mail/blob/main/client.go#L327-L329 but it didn't.

**Comment by wneessen** [comment]
Hi, thanks for the request.

This is actually a false-positive. When used without the `mail.WithSMTPAuth` option, the library in fact does send mails without any authentication - if the mail server allows this.

As you stated in `2.` the `550 relay not permitted` message means, that the mail server does not allow relaying mails - meaning sending mails without being either authenticated or being IP whitelisted. I just confirmed with my local Postfix installation, that I am able to send mails without prior authentication.

I suggest that you check the local mail server configuration to see if local relaying is allowed or not.
In Postfix you can accomplish this by 

```
mynetworks = 127.0.0.0/8
smtpd_recipient_restrictions = permit_mynetworks [....]
```

**Comment by kolaente** [comment]
Thanks for the explanation! Looks like my lack of mail server knowledge is to blame here :)

I've checked the implementation and config again and it seems to work fine when I run everything on a server that's allowed to talk to the mail server.

**Comment by mitar** [comment]
I also got confused how to configure no-authentication SMTP. Luckily I found this issue.

**Comment by wneessen** [comment]
Gald this helped you. I'll consider adding a FAQ section to the go-mail website and adding this, as it seems a common issue.

**Comment by mitar** [comment]
Maybe easier is to define `SMTPAuthType` `None` which equals to an empty string. This is what I did in my own codebase now.

**Comment by wneessen** [comment]
Gotta evaluate that.
