### ISSUE TITLE
"Use of closed network connection" error when using concurrently

### ISSUE THREAD

**Issue by jgimenez** [wneessen/go-mail#380]
### Description

This is more a PSA than an actual bug report.

When sending messages using goroutines, sending randomly fails with an error like this:

```
send failed: sending SMTP MAIL FROM command: use of closed network connection, use of closed network connection, affected message ID: xxxx
```

### To Reproduce

This is a simplified version:

```go
client, err := gomail.NewClient(...)

for range 100 {
	go func() {
		m := gomail.NewMsg()
		m.FromFormat("name", "lala@example.com")
		m.AddTo(toAddress)
		m.SetBodyString(gomail.TypeTextPlain, "Hello")
        	err := client.DialAndSend(m) // err here is not nil about 15-20% of the times
	}
}
```

### Expected behaviour

No errors (or maybe one random error every now and then if the network or server is down).

### Attempted Fixes

Instantiate a NewClient for every message sent. This works.

### Additional context

I have the feeling this library intends to be thread-safe but it's not (I guessed that because I see some mutexes). So maybe this is a bug.

I suggest making `DialAndSend` thread-safe, or clearly documenting that a client should not be used from multiple goroutines (or locking should be used).

**Comment by wneessen** [comment]
Thanks for reporting @jgimenez. Threat-safety has been introduced in a recent release with the intention that the Client can be reused within the go-routines, so that you don't have to use DialAndSend but can just use Send on an open connection similar to what we do in this test:

```go
                wg := sync.WaitGroup{}
                for id, curMessage := range messages {
                        wg.Add(1)
                        go func(curMsg *Msg, curID int) {
                                defer wg.Done()
                                if goroutineErr := client.Send(curMsg); err != nil {
                                        t.Errorf("failed to send message with ID %d: %s", curID, goroutineErr)
                                }
                        }(curMessage, id)
                }
                wg.Wait()
```

But I agree that DialAndSend should also be thread-safe to fullfil the claim. I'll have a look at this and hopefully introduce a fix soon.
