### ISSUE TITLE
Add GetAddrHeader

### ISSUE THREAD

**Issue by oschwald** [wneessen/go-mail#80]
### Is your feature request related to a problem? Please describe.

I am currently porting some code from `github.com/go-mail/mail` and I noticed that there is no way to access the the individual `addrHeader` values. The closest option seems to be `GetRecipients`, but there is no way to distinguish the different recipient types with that. For us, this primarily comes up in test code.

### Describe the solution you'd like

I would be fine with something like `GetAddrHeader` that was similar to `GetGenHeader`.

### Describe alternatives you've considered

1. `GetTo`, `GetCc`, `GetBcc`, etc. This would be fine for my use case and may more closely follow the current API design.
2. `GetHeader` that looked up address headers in `addrHeaders` and general headers in `genHeaders`. Right now, it kind of feels like implementation details of the library are leaking out via `GetGenHeader`. That said, I think if this were to be done, `SetHeader` should probably be updated to put address headers in `addrHeader`. 

If something like (2) is not done, it might make sense to deprecate `SetHeader` and add `SetGenHeader` to make the API more consistent and to make it clear that address headers cannot be set with it. I almost did not notice this when porting to this library.

**Comment by wneessen** [comment]
I agree, definitely something that is needed. This is also helpful for middlewares. Thanks for the proposed solutions. I'll check which one would work best

**Comment by oschwald** [comment]
Thank you!
