### ISSUE TITLE
Error from body writer is ignored

### ISSUE THREAD

**Issue by oschwald** [wneessen/go-mail#81]
### Description

If you set a body writer with `SetBodyWriter` and the writer fails with an error, `(*Msg).WriteTo` will not return an error itself.

### To Reproduce

Run:

```
package main

import (
	"errors"
	"fmt"
	"io"

	"github.com/wneessen/go-mail"
)

func main() {
	m := mail.NewMsg()

	m.SetBodyWriter(
		mail.TypeTextPlain,
		func(io.Writer) (int64, error) {
			return 0, errors.New("failed!")
		},
	)

	_, err := m.WriteTo(io.Discard)
	fmt.Println(err)
}
```

### Expected behaviour

The above prints out `<nil>`. I would expect the body writer error to cause `WriteTo` to return an error, resulting in the program outputting `failed!` or a wrapped version of it. Right now, there is no indication that an error occurred.

**Comment by wneessen** [comment]
Thanks for the report. That indeed doesn't sound right. I'll have a look what's going on there.

**Comment by oschwald** [comment]
Thanks for the quick fix on this.
